sudo: required
services:
    - docker

before_install:
  - docker build -t kichyrag76/fibmulti-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kichyrag76/fibmulti-test npm test -- --coverage

after_success:
  - docker build -t kichyrag76/fibmulti-client ./client
  - docker build -t kichyrag76/fibmulti-nginx ./ngnix
  - docker build -t kichyrag76/fibmulti-server ./server 
  - docker build -t kichyrag76/fibmulti-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take to those images and push them to docker hub
  - docker push kichyrag76/fibmulti-client
  - docker push kichyrag76/fibmulti-nginx
  - docker push kichyrag76/fibmulti-server
  - docker push kichyrag76/fibmulti-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app:  "fibMultiContainer"
  env:  "Fibmulticontainer-env"
  bucket_name:  "elasticbeanstalk-us-east-2-897163456416"
  bucket_path:  "fibmulti-container"
  on:
    branch: master
  access_key_id:  "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

